### ISSUE TITLE
Can not load

### ISSUE THREAD

**Issue by ca654321** [nickwph/JavPlexAgent.bundle#1]
I tried on my NAS, it not working and so heavy. Normal bundle is around 1MB, JavPlexAgent.bundle is 200MB after unzip

**Comment by nickwph** [comment]
Hi @ca654321 unfortunately yes it's large. 

If you want it smaller you can delete `Contents/Libraries/Shared/numpy`, it's ~70MB. However you will lose the ability to get high resolution posters.

And that you mentioned it's not working. Please provide the error messages appeared in `/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Logs/PMS Plugin Logs/com.nicholasworkshop.javplexagents.log` from your NAS, alternative you can send over the files.

😄

**Comment by ca654321** [comment]
[com.nicholasworkshop.javplexagents.log](https://github.com/nickwph/JavPlexAgent.bundle/files/4496902/com.nicholasworkshop.javplexagents.log)
Here you go, thanks you

**Comment by nickwph** [comment]
From your log your Plex were not able to load the library `pyquery`. I made some updates to the libraries. Please try again with the latest `master` branch when you have time. 😄

**Comment by ca654321** [comment]
It working already, great 👯

**Comment by nickwph** [comment]
Awesome! 👯 

I am closing this issue then.
