### ISSUE TITLE
Trying to finish up Genre code

### ISSUE THREAD

**Issue by ktrankc** [nickwph/JavPlexAgent.bundle#2]
Hi Nick,

I stumbled upon your repo and really enjoyed what you have done so far.  I noticed you did not finish the Genre code fanza_update.py:

```
# same for genre, just like actress
```

So I attempted to add:

```
    metadata.genres.clear()
    if 'genre' in item.iteminfo:
        for category in item.iteminfo.genre:
            genre = metadata.genres.new()
            genre.name = category.name
            Log.Info(u"Processing genre data: {}".format(genre.name))
```

I also added in framework/plex_metadata.py:
```

class Genre(object):
    name = "Stub"

class GenreList(list):
    def new(self):
        genre = Genre()
        list.append(self, genre)
        return genre

    def clear(self):
        del self[:]
```

and change:

```
`genres = GenreList() # Stub
```

But I am getting a framework error about how metadata.genres.new() is not recognized in the framework.

**Comment by nickwph** [comment]
Hi! I am glad to hear you trying it out. I think `metadata.genre` is a `Set[str]` type, and it doesn't need to special class to handle the creation.

I will work on that when I have time, but feel free to test it out. 😄

**Comment by ktrankc** [comment]
Oh wow, you do reply :).  I got it working last night and then I saw your message.

```
    metadata.genres.clear()
    if 'genre' in item.iteminfo:
        for category in item.iteminfo.genre:
            metadata.genres.add(category.name)
            Log.Info(u"Processing genre data: {}".format(category.name))

```

I added some translation stuff to your updaters and it is working super well!

**Comment by nickwph** [comment]
Awesome! glad to hear that!
