### ISSUE TITLE
How are you building the Shared Library packages

### ISSUE THREAD

**Issue by ktrankc** [nickwph/JavPlexAgent.bundle#4]
So I am trying to add more Shared Libraries (google translate).

I only have a Windows env so I am doing the following:

Install Python 2.7
Set export variable to UCS2
Install Virtual ENV
Install Source (then realized windows does not use source)
virtualenv Virtualenv
Virtualenv\Scripts\activate
easy_install google-cloud-translate=2.0.1
Virtualenv\Scripts\deactivate.bat

Copied libs over to DSM (Synology platform)

**Comment by nickwph** [comment]
I am not sure if `google-cloud-translate` has any native libraries. However you should be able to use it by copying the libraries into `Libraries/Shared` or `Libraries/Windows/i386`.

**Comment by nickwph** [comment]
closing this as there was no more replies.
