### ISSUE TITLE
Same results on every query

### ISSUE THREAD

**Issue by raenoll** [nickwph/JavPlexAgent.bundle#5]
I got the same results on every search.

今天第一次装完之后好像正常搜索过几次，然后后来就都不行了。在默认为当前搜刮器的库搜索全部无结果，在非默认为当前搜刮器的库手动搜索任意内容结果全部一样。
重装了好几次，发现如果不给插件目录更改至plex用户就无法创建资料库。

OS: Debian 10

**Comment by nickwph** [comment]
Sorry I don't understand your issue. Maybe you could try clearing the cache.

**Comment by nickwph** [comment]
Closing this issue as there is no futher information provided.
