### ISSUE TITLE
Debian compatibility

### ISSUE THREAD

**Issue by raenoll** [nickwph/JavPlexAgent.bundle#8]
Is it compatible on debian 10? I cloned the latest but Plex didn't find this plugin. I also checked permission.

**Comment by nickwph** [comment]
Cloning wont work because the project has turned into compiling based project. You need to download the `linux` version from https://github.com/nickwph/JavPlexAgent.bundle/releases

**Comment by raenoll** [comment]
It's available now. Thanks. I'll report later.
I tried this agent before, but something was wrong at that time.
