### ISSUE TITLE
Cover Issue

### ISSUE THREAD

**Issue by raenoll** [nickwph/JavPlexAgent.bundle#9]
1. Scan with a fanza video.
2. Auto match by incorrect title A (top in search).
3. Manual match to title B.
4. Cover isn't changed to B, but still A.

debian 10, pms 1.21.1.3876

**Comment by raenoll** [comment]
Also, if a video preview thumbnail is generated before the match, cover can't be replaced. This can be solved by reinstalling the plugin.

**Comment by nickwph** [comment]
@raenoll this is a limitaton from Plex. You have to change it by editing the media. 

Another option is to clear all metadata cache in plex and let it redownload, however doing this will clear all media metadata data. https://github.com/nickwph/JavPlexAgent.bundle/blob/master/docs/contribute-ubuntu.md#delete-and-reset-cached-images

**Comment by raenoll** [comment]
I have a huge library and it's not an option to delete metadata. I tried to delete cache directory only, but it seems not working.

Is there any way I can find the exact metadata / media directory which is affected?
